package com.vcp.mobile.contract

import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

class PluginContractTest {
    private val pluginRoot = findPluginRoot()

    private fun findPluginRoot(): File {
        var dir = File(System.getProperty("user.dir") ?: ".").canonicalFile
        repeat(8) {
            val direct = File(dir, "src-tauri/plugins/vcp-mobile")
            if (File(direct, "src/lib.rs").exists()) {
                return direct
            }

            val androidModule = File(dir, "src/lib.rs")
            if (androidModule.exists() && File(dir, "guest-js/index.ts").exists()) {
                return dir
            }

            dir = dir.parentFile ?: return@repeat
        }
        error("无法定位 tauri-plugin-vcp-mobile 根目录，user.dir=${System.getProperty("user.dir")}")
    }

    @Test
    fun defaultPermissionContainsAllRegisteredPluginCommands() {
        val libRs = File(pluginRoot, "src/lib.rs").readText()
        val defaultToml = File(pluginRoot, "permissions/default.toml").readText()

        val registeredCommands = Regex("(?:screen|stream|system)::([a-zA-Z0-9_]+)")
            .findAll(libRs)
            .map { it.groupValues[1] }
            .toSet()

        val missing = registeredCommands.filter { command ->
            !defaultToml.contains("\"$command\"")
        }

        assertTrue("default.toml 缺少插件命令授权: $missing", missing.isEmpty())
    }

    @Test
    fun dormantAssistantBridgesRemainSourceOnlyAndUnregistered() {
        val systemRs = File(pluginRoot, "src/system.rs").readText()
        val kotlinPlugin = File(
            pluginRoot,
            "android/src/main/java/com/vcp/mobile/VcpMobilePlugin.kt",
        ).readText()
        val pluginManifest = File(pluginRoot, "android/src/main/AndroidManifest.xml").readText()
        val exposureFiles = listOf(
            "src/lib.rs",
            "build.rs",
            "permissions/default.toml",
            "permissions/all.toml",
        ).associateWith { File(pluginRoot, it).readText() }
        val dormantCommands = listOf("request_overlay_permission", "toggle_floating_ball")

        assertTrue(
            "Rust 技术资产应保留",
            dormantCommands.all { systemRs.contains("pub fn $it") },
        )
        assertTrue(
            "Kotlin 技术资产应保留",
            kotlinPlugin.contains("fun requestOverlayPermission(") &&
                kotlinPlugin.contains("fun toggleFloatingBall("),
        )
        assertTrue(
            "通用权限检查不得实例化或读取休眠的悬浮窗资产",
            !kotlinPlugin.contains("hasOverlayPermission(") &&
                !kotlinPlugin.contains("result.put(\"overlay\"") &&
                !systemRs.contains("pub overlay:"),
        )
        assertTrue(
            "休眠功能不得继续声明悬浮窗权限",
            !pluginManifest.contains("android.permission.SYSTEM_ALERT_WINDOW"),
        )
        dormantCommands.forEach { command ->
            exposureFiles.forEach { (path, content) ->
                assertTrue("$path 不得继续暴露 $command", !content.contains(command))
            }
            assertTrue(
                "注销命令后必须删除 autogenerated permission: $command",
                !File(pluginRoot, "permissions/autogenerated/commands/$command.toml").exists(),
            )
        }
    }

    @Test
    fun guestJsStopStreamServicePassesAgentNameArgument() {
        val guestJs = File(pluginRoot, "guest-js/index.ts").readText()

        assertTrue(
            "stopStreamService 应接收 agentName 参数",
            Regex("function\\s+stopStreamService\\s*\\(\\s*agentName\\s*:\\s*string\\s*\\)").containsMatchIn(guestJs),
        )
        assertTrue(
            "stopStreamService invoke 应传递 { agentName }",
            guestJs.contains("plugin:vcp-mobile|stop_streaming_service") && guestJs.contains("{ agentName }"),
        )
    }

    @Test
    fun rustRunMobilePluginMethodNamesExistInKotlinPlugin() {
        val rustSources = listOf("src/system.rs", "src/stream.rs", "src/cli.rs")
            .map { File(pluginRoot, it).readText() }
            .joinToString("\n")
        val kotlinPlugin = File(
            pluginRoot,
            "android/src/main/java/com/vcp/mobile/VcpMobilePlugin.kt",
        ).readText()

        val methodNames = Regex("run_mobile_plugin(?:::<[^>]+>)?\\(\\s*\"([A-Za-z0-9_]+)\"")
            .findAll(rustSources)
            .map { it.groupValues[1] }
            .toSet()

        val missing = methodNames.filter { method ->
            !Regex("fun\\s+$method\\s*\\(").containsMatchIn(kotlinPlugin)
        }

        assertTrue("Rust run_mobile_plugin 方法在 Kotlin 中不存在: $missing", missing.isEmpty())
    }

    @Test
    fun helperConnectionAndSessionCleanupUseIdentityChecks() {
        val helper = File(
            pluginRoot,
            "android/src/main/java/com/vcp/mobile/service/SseProxyService.kt",
        ).readText()

        assertTrue("resume 连接必须按引用同一性解绑", helper.contains("activeConnection !== connection"))
        assertTrue("重复 requestId 必须用 putIfAbsent 拒绝覆盖", helper.contains("activeSessions.putIfAbsent(requestId, session)"))
        assertTrue(
            "session 删除必须携带实例身份",
            helper.contains("activeSessions.remove(requestId, session)") ||
                helper.contains("activeSessions.remove(session.requestId, session)"),
        )
        assertTrue("EventSource 安装必须复核 session owner", helper.contains("isServiceRunning && isCurrentSession(session)"))
        assertTrue("失去 owner 的 EventSource 必须立即取消", helper.contains("source.cancel()"))
        assertTrue("旧 raw output 所有权字段不应残留", !helper.contains("activeSocketOutputStream"))
        assertTrue("helper 不得再用静音音频伪装媒体保活", !helper.contains("MediaPlayer"))
        assertTrue("stop 必须读取调用方期望代次", helper.contains("request.optLong(\"generation\", -1L)"))
        assertTrue("stop 必须精确匹配 session 代次", helper.contains("session.generation != expectedGeneration"))
        assertTrue(
            "stop ACK 必须同时返回代次与实际停止结果",
            helper.contains("\"stop_ack\"") &&
                helper.contains("put(\"generation\"") &&
                helper.contains("put(\"stopped\", stopped)"),
        )
    }

    @Test
    fun helperIsLazyAndInsetsAreFrameCoalesced() {
        val kotlinPlugin = File(
            pluginRoot,
            "android/src/main/java/com/vcp/mobile/VcpMobilePlugin.kt",
        ).readText()
        val initBody = Regex("init\\s*\\{([\\s\\S]*?)\\n\\s*}").find(kotlinPlugin)?.groupValues?.get(1).orEmpty()
        val insets = File(
            pluginRoot,
            "android/src/main/java/com/vcp/mobile/KeyboardInsetsManager.kt",
        ).readText()

        assertTrue("helper 不得在插件 init 时无条件启动", !initBody.contains("startHelperServiceInternal"))
        assertTrue("Insets 必须按显示帧合并", insets.contains("postOnAnimation(frameCallback)"))
        assertTrue(
            "Insets manager 必须支持解绑并归零 IME",
            insets.contains("fun detach()") && insets.contains("previous?.withoutIme()"),
        )
        val replayAssignment = insets.indexOf("window.__VCP_NATIVE_INSETS__ =")
        val eventDispatch = insets.indexOf("window.dispatchEvent(new CustomEvent('vcp-keyboard-inset'")
        assertTrue(
            "Insets snapshot 必须先写入 window replay 再派发事件",
            replayAssignment >= 0 && eventDispatch > replayAssignment,
        )
    }

    @Test
    fun pluginExecutorsAreIsolatedBoundedAndCancellable() {
        val kotlinPlugin = File(
            pluginRoot,
            "android/src/main/java/com/vcp/mobile/VcpMobilePlugin.kt",
        ).readText()

        assertTrue("OOM guard 必须使用 fixed-delay scheduler", kotlinPlugin.contains("scheduleWithFixedDelay"))
        assertTrue("Root 命令必须使用独立 executor", kotlinPlugin.contains("executorDomains.rootExecutor"))
        assertTrue("文件任务必须使用独立 executor", kotlinPlugin.contains("executorDomains.fileIoExecutor"))
        assertTrue("文件域默认保持串行语义", kotlinPlugin.contains("fileThreadCount: Int = 1"))
        assertTrue("执行队列必须有界", kotlinPlugin.contains("ArrayBlockingQueue"))
        assertTrue("非 Root 设备只探测一次后退出", kotlinPlugin.contains("if (!Shell.getShell().isRoot)"))
        assertTrue("销毁必须立即取消执行域", kotlinPlugin.contains("executorDomains.shutdownNow()"))
    }

    @Test
    fun rawJniAndGuardianScreenRequestsShareOrArbitration() {
        val kotlinPlugin = File(
            pluginRoot,
            "android/src/main/java/com/vcp/mobile/VcpMobilePlugin.kt",
        ).readText()
        val rustScreen = File(pluginRoot, "src/screen.rs").readText()

        assertTrue(
            "屏幕常亮必须由 manual OR Guardian 统一仲裁",
            kotlinPlugin.contains("manualRequested || guardianRequested"),
        )
        assertTrue(
            "Raw JNI owner 必须进入统一仲裁器",
            rustScreen.contains("ScreenKeepOnArbiter") && rustScreen.contains("setManualRequested"),
        )
        assertTrue(
            "Rust clear 不得绕过另一 owner 直接清 Window flag",
            !rustScreen.contains("clearFlags"),
        )
    }

    @Test
    fun rustMobilePluginCallsDoNotHoldHandleMutexWhileWaitingForKotlin() {
        val libRs = File(pluginRoot, "src/lib.rs").readText()
        val commandSources = listOf("src/system.rs", "src/stream.rs", "src/cli.rs")
            .map { File(pluginRoot, it).readText() }
            .joinToString("\n")

        assertTrue("PluginHandle 必须在锁内 clone", libRs.contains(".as_ref()\n            .cloned()"))
        assertTrue("command 必须通过短锁 helper 获取句柄", commandSources.contains("mobile_plugin_handle()?"))
        assertTrue("command 不得直接持锁跨 run_mobile_plugin", !commandSources.contains("plugin_handle.lock()"))
    }

    @Test
    fun cliProcessHostBridgeIsInternalAndCannotBypassRustJobOwner() {
        val rustCli = File(pluginRoot, "src/cli.rs").readText()
        val kotlinPlugin = File(
            pluginRoot,
            "android/src/main/java/com/vcp/mobile/VcpMobilePlugin.kt",
        ).readText()
        val processHost = File(
            pluginRoot,
            "android/src/main/java/com/vcp/mobile/cli/CliProcessHost.kt",
        ).readText()
        val publicSurfaces = listOf(
            "src/lib.rs",
            "build.rs",
            "permissions/default.toml",
            "permissions/all.toml",
            "guest-js/index.ts",
        ).associateWith { File(pluginRoot, it).readText() }
        val internalMethods = listOf(
            "prepareCliRuntime",
            "startCliProcess",
            "inspectCliProcess",
            "cancelCliProcess",
        )
        val internalRustFunctions = listOf(
            "prepare_cli_runtime_inner",
            "start_cli_process_inner",
            "inspect_cli_process_inner",
            "cancel_cli_process_inner",
        )

        internalMethods.forEach { method ->
            assertTrue("Rust internal bridge 缺少 method $method", rustCli.contains("\"$method\""))
            assertTrue("Kotlin thin delegate 缺少 $method", kotlinPlugin.contains("fun $method("))
            publicSurfaces.forEach { (path, content) ->
                assertTrue("$path 不得公开内部 CLI method $method", !content.contains(method))
            }
        }
        internalRustFunctions.forEach { function ->
            assertTrue("Rust CLI bridge 缺少 $function", rustCli.contains("pub async fn $function"))
            assertTrue("内部 bridge 不得成为 #[tauri::command]", !rustCli.contains("#[tauri::command]\npub async fn $function"))
        }
        assertFalse("Kotlin plugin 不应再注册本地语义资产 bridge", kotlinPlugin.contains("prepareCliSemanticAssets"))
        assertTrue("CLI ProcessHost 不得调用 Root/libsu", !processHost.contains("libsu") && !processHost.contains("Shell.getShell"))
        assertTrue("CLI ProcessHost 必须以精确 Job lease 接入 Guardian", processHost.contains("CliNotificationTarget"))
        assertTrue("CLI ProcessHost 必须由应用进程 singleton 持有", processHost.contains("object CliProcessHostOwner"))
        assertTrue("CLI ProcessHost 不得新增 localhost bridge", !processHost.contains("ServerSocket") && !processHost.contains("localhost"))
        assertTrue("plugin onDestroy 不得终止应用进程所有 CLI Job", !kotlinPlugin.contains("cliProcessHost.close()"))
        assertTrue("plugin 必须从应用进程 owner 获取 CLI ProcessHost", kotlinPlugin.contains("CliProcessHostOwner.get(activity.applicationContext)"))
    }

    @Test
    fun cliProcessHostFreezesPrivateOutputAndWholeGroupCleanupContracts() {
        val processHost = File(
            pluginRoot,
            "android/src/main/java/com/vcp/mobile/cli/CliProcessHost.kt",
        ).readText()
        val buildScript = File(
            pluginRoot,
            "../../runtime-assets/vcp-cli/build/build_proot.sh",
        ).canonicalFile.readText()
        val commandProfile = File(
            pluginRoot,
            "../../runtime-assets/vcp-cli/command-profile.json",
        ).canonicalFile.readText()

        assertTrue("host environment 必须先 clear 防止继承密钥", processHost.contains("processBuilder.environment().apply {\n                clear()"))
        assertTrue("PRoot 必须使用私有 PROOT_TMP_DIR", processHost.contains("\"PROOT_TMP_DIR\" to prootTmpPath"))
        assertTrue("PRoot 必须显式使用 APK nativeLibraryDir loader", processHost.contains("\"PROOT_LOADER\" to prootLoaderPath"))
        assertTrue("PRoot loader 必须从 nativeLibraryDir 解析", processHost.contains("verifyNativeExecutable(\n            nativeLibraryDirectory,\n            PROOT_LOADER_LIBRARY_NAME"))
        assertTrue("APK native ELF 必须在原始 path 上 NOFOLLOW 校验", processHost.contains("LinkOption.NOFOLLOW_LINKS"))
        assertTrue("APK native ELF 必须拒绝 symlink", processHost.contains("attributes.isRegularFile && !attributes.isSymbolicLink"))
        assertTrue("PRoot 构建必须禁用 bundled loader", buildScript.contains("PROOT_UNBUNDLE_LOADER=\"${'$'}unbundled_loader_fallback\""))
        assertTrue("构建必须单独冻结 loader ELF", buildScript.contains("built_loader=\"${'$'}proot_root/src/loader/loader\""))
        assertTrue("profile 必须声明 unbundled loader", commandProfile.contains("\"loaderMode\": \"unbundled_required\""))
        assertTrue("profile 必须固定 APK loader 名", commandProfile.contains("libvcp_proot_loader.so"))
        assertTrue("PRoot 必须在退出时清理全部 tracee", processHost.contains("\"--kill-on-exit\""))
        assertTrue("prepare 必须回显旧投影清理 root", processHost.contains("put(\"projectionRootPath\""))
        assertFalse("ProcessHost 不应再准备本地语义资产", processHost.contains("prepareSemantic"))
        assertFalse("ProcessHost 不应再注入 River 环境变量", processHost.contains("VCP_RIVER_CONTEXT_FILE"))
        assertFalse("ProcessHost 不应再接受 River projection", processHost.contains("riverContextProjection"))
        assertTrue("用户命令必须保持 Bash -lc 独立 argv", processHost.contains("add(\"/bin/bash\")\n    add(\"-lc\")\n    add(command)"))
        assertTrue("不允许向 guest 暴露 /sys", !processHost.contains("\"/sys\""))
        assertTrue("host-managed output 不得 bind 到 guest", !processHost.contains("outputPath:/output") && !processHost.contains("prepared.output.absolutePath:/output"))
        assertTrue("不得把完整 projection root 暴露给 guest", !processHost.contains("prepared.projectionRoot.absolutePath:/"))
        assertTrue("canonical Skills 不得 bind 给 fake-root guest", !processHost.contains(":/skills"))
        assertTrue("signal 前必须复核完整 process identity", processHost.contains("current.startTimeTicks == handle.identity.startTimeTicks"))
        assertTrue("取消必须向负 PGID 发信号", processHost.contains("Os.kill(-pgid, signal)"))
        assertTrue("强杀前必须给 PRoot tracee 清理窗口", processHost.indexOf("OsConstants.SIGQUIT") < processHost.indexOf("OsConstants.SIGKILL"))
        assertTrue("普通退出也必须清理残留 process group", processHost.contains("terminateOwnedGroup(handle, ORPHAN_GRACE_MS)"))
        assertTrue("Exited 前必须等待 stdout/stderr drain", processHost.contains("drainReadersForTerminal(handle)") && processHost.contains("!handle.stdoutReader.isAlive && !handle.stderrReader.isAlive"))
        assertTrue("完成 handle 必须可安全淘汰", processHost.contains("completed.isCompleted()") && processHost.contains("handles.remove(key, completed)"))
    }
}
