package com.vcp.mobile.contract

import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

class PluginContractTest {
    private val pluginRoot = findPluginRoot()

    private fun findPluginRoot(): File {
        var dir = File(System.getProperty("user.dir") ?: ".").canonicalFile
        repeat(8) {
            val direct = File(dir, "src-tauri/plugins/vcp-mobile")
            if (File(direct, "src/lib.rs").exists()) {
                return direct
            }

            val androidModule = File(dir, "src/lib.rs")
            if (androidModule.exists() && File(dir, "guest-js/index.ts").exists()) {
                return dir
            }

            dir = dir.parentFile ?: return@repeat
        }
        error("无法定位 tauri-plugin-vcp-mobile 根目录，user.dir=${System.getProperty("user.dir")}")
    }

    @Test
    fun defaultPermissionContainsAllRegisteredPluginCommands() {
        val libRs = File(pluginRoot, "src/lib.rs").readText()
        val defaultToml = File(pluginRoot, "permissions/default.toml").readText()

        val registeredCommands = Regex("(?:screen|stream|system)::([a-zA-Z0-9_]+)")
            .findAll(libRs)
            .map { it.groupValues[1] }
            .toSet()

        val missing = registeredCommands.filter { command ->
            !defaultToml.contains("\"$command\"")
        }

        assertTrue("default.toml 缺少插件命令授权: $missing", missing.isEmpty())
    }

    @Test
    fun dormantAssistantBridgesRemainSourceOnlyAndUnregistered() {
        val systemRs = File(pluginRoot, "src/system.rs").readText()
        val kotlinPlugin = File(
            pluginRoot,
            "android/src/main/java/com/vcp/mobile/VcpMobilePlugin.kt",
        ).readText()
        val pluginManifest = File(pluginRoot, "android/src/main/AndroidManifest.xml").readText()
        val exposureFiles = listOf(
            "src/lib.rs",
            "build.rs",
            "permissions/default.toml",
            "permissions/all.toml",
        ).associateWith { File(pluginRoot, it).readText() }
        val dormantCommands = listOf("request_overlay_permission", "toggle_floating_ball")

        assertTrue(
            "Rust 技术资产应保留",
            dormantCommands.all { systemRs.contains("pub fn $it") },
        )
        assertTrue(
            "Kotlin 技术资产应保留",
            kotlinPlugin.contains("fun requestOverlayPermission(") &&
                kotlinPlugin.contains("fun toggleFloatingBall("),
        )
        assertTrue(
            "通用权限检查不得实例化或读取休眠的悬浮窗资产",
            !kotlinPlugin.contains("hasOverlayPermission(") &&
                !kotlinPlugin.contains("result.put(\"overlay\"") &&
                !systemRs.contains("pub overlay:"),
        )
        assertTrue(
            "休眠功能不得继续声明悬浮窗权限",
            !pluginManifest.contains("android.permission.SYSTEM_ALERT_WINDOW"),
        )
        dormantCommands.forEach { command ->
            exposureFiles.forEach { (path, content) ->
                assertTrue("$path 不得继续暴露 $command", !content.contains(command))
            }
            assertTrue(
                "注销命令后必须删除 autogenerated permission: $command",
                !File(pluginRoot, "permissions/autogenerated/commands/$command.toml").exists(),
            )
        }
    }

    @Test
    fun guestJsStopStreamServicePassesAgentNameArgument() {
        val guestJs = File(pluginRoot, "guest-js/index.ts").readText()

        assertTrue(
            "stopStreamService 应接收 agentName 参数",
            Regex("function\\s+stopStreamService\\s*\\(\\s*agentName\\s*:\\s*string\\s*\\)").containsMatchIn(guestJs),
        )
        assertTrue(
            "stopStreamService invoke 应传递 { agentName }",
            guestJs.contains("plugin:vcp-mobile|stop_streaming_service") && guestJs.contains("{ agentName }"),
        )
    }

    @Test
    fun rustRunMobilePluginMethodNamesExistInKotlinPlugin() {
        val rustSources = listOf("src/system.rs", "src/stream.rs")
            .map { File(pluginRoot, it).readText() }
            .joinToString("\n")
        val kotlinPlugin = File(
            pluginRoot,
            "android/src/main/java/com/vcp/mobile/VcpMobilePlugin.kt",
        ).readText()

        val methodNames = Regex("run_mobile_plugin(?:::<[^>]+>)?\\(\\s*\"([A-Za-z0-9_]+)\"")
            .findAll(rustSources)
            .map { it.groupValues[1] }
            .toSet()

        val missing = methodNames.filter { method ->
            !Regex("fun\\s+$method\\s*\\(").containsMatchIn(kotlinPlugin)
        }

        assertTrue("Rust run_mobile_plugin 方法在 Kotlin 中不存在: $missing", missing.isEmpty())
    }

    @Test
    fun helperConnectionAndSessionCleanupUseIdentityChecks() {
        val helper = File(
            pluginRoot,
            "android/src/main/java/com/vcp/mobile/service/SseProxyService.kt",
        ).readText()

        assertTrue("resume 连接必须按引用同一性解绑", helper.contains("activeConnection !== connection"))
        assertTrue("重复 requestId 必须用 putIfAbsent 拒绝覆盖", helper.contains("activeSessions.putIfAbsent(requestId, session)"))
        assertTrue(
            "session 删除必须携带实例身份",
            helper.contains("activeSessions.remove(requestId, session)") ||
                helper.contains("activeSessions.remove(session.requestId, session)"),
        )
        assertTrue("EventSource 安装必须复核 session owner", helper.contains("isServiceRunning && isCurrentSession(session)"))
        assertTrue("失去 owner 的 EventSource 必须立即取消", helper.contains("source.cancel()"))
        assertTrue("旧 raw output 所有权字段不应残留", !helper.contains("activeSocketOutputStream"))
        assertTrue("helper 不得再用静音音频伪装媒体保活", !helper.contains("MediaPlayer"))
        assertTrue("stop 必须读取调用方期望代次", helper.contains("request.optLong(\"generation\", -1L)"))
        assertTrue("stop 必须精确匹配 session 代次", helper.contains("session.generation != expectedGeneration"))
        assertTrue(
            "stop ACK 必须同时返回代次与实际停止结果",
            helper.contains("\"stop_ack\"") &&
                helper.contains("put(\"generation\"") &&
                helper.contains("put(\"stopped\", stopped)"),
        )
    }

    @Test
    fun helperIsLazyAndInsetsAreFrameCoalesced() {
        val kotlinPlugin = File(
            pluginRoot,
            "android/src/main/java/com/vcp/mobile/VcpMobilePlugin.kt",
        ).readText()
        val initBody = Regex("init\\s*\\{([\\s\\S]*?)\\n\\s*}").find(kotlinPlugin)?.groupValues?.get(1).orEmpty()
        val insets = File(
            pluginRoot,
            "android/src/main/java/com/vcp/mobile/KeyboardInsetsManager.kt",
        ).readText()

        assertTrue("helper 不得在插件 init 时无条件启动", !initBody.contains("startHelperServiceInternal"))
        assertTrue("Insets 必须按显示帧合并", insets.contains("postOnAnimation(frameCallback)"))
        assertTrue(
            "Insets manager 必须支持解绑并归零 IME",
            insets.contains("fun detach()") && insets.contains("previous?.withoutIme()"),
        )
        val replayAssignment = insets.indexOf("window.__VCP_NATIVE_INSETS__ =")
        val eventDispatch = insets.indexOf("window.dispatchEvent(new CustomEvent('vcp-keyboard-inset'")
        assertTrue(
            "Insets snapshot 必须先写入 window replay 再派发事件",
            replayAssignment >= 0 && eventDispatch > replayAssignment,
        )
    }

    @Test
    fun pluginExecutorsAreIsolatedBoundedAndCancellable() {
        val kotlinPlugin = File(
            pluginRoot,
            "android/src/main/java/com/vcp/mobile/VcpMobilePlugin.kt",
        ).readText()

        assertTrue("OOM guard 必须使用 fixed-delay scheduler", kotlinPlugin.contains("scheduleWithFixedDelay"))
        assertTrue("Root 命令必须使用独立 executor", kotlinPlugin.contains("executorDomains.rootExecutor"))
        assertTrue("文件任务必须使用独立 executor", kotlinPlugin.contains("executorDomains.fileIoExecutor"))
        assertTrue("文件域默认保持串行语义", kotlinPlugin.contains("fileThreadCount: Int = 1"))
        assertTrue("执行队列必须有界", kotlinPlugin.contains("ArrayBlockingQueue"))
        assertTrue("非 Root 设备只探测一次后退出", kotlinPlugin.contains("if (!Shell.getShell().isRoot)"))
        assertTrue("销毁必须立即取消执行域", kotlinPlugin.contains("executorDomains.shutdownNow()"))
    }

    @Test
    fun rawJniAndGuardianScreenRequestsShareOrArbitration() {
        val kotlinPlugin = File(
            pluginRoot,
            "android/src/main/java/com/vcp/mobile/VcpMobilePlugin.kt",
        ).readText()
        val rustScreen = File(pluginRoot, "src/screen.rs").readText()

        assertTrue(
            "屏幕常亮必须由 manual OR Guardian 统一仲裁",
            kotlinPlugin.contains("manualRequested || guardianRequested"),
        )
        assertTrue(
            "Raw JNI owner 必须进入统一仲裁器",
            rustScreen.contains("ScreenKeepOnArbiter") && rustScreen.contains("setManualRequested"),
        )
        assertTrue(
            "Rust clear 不得绕过另一 owner 直接清 Window flag",
            !rustScreen.contains("clearFlags"),
        )
    }

    @Test
    fun rustMobilePluginCallsDoNotHoldHandleMutexWhileWaitingForKotlin() {
        val libRs = File(pluginRoot, "src/lib.rs").readText()
        val commandSources = listOf("src/system.rs", "src/stream.rs")
            .map { File(pluginRoot, it).readText() }
            .joinToString("\n")

        assertTrue("PluginHandle 必须在锁内 clone", libRs.contains(".as_ref()\n            .cloned()"))
        assertTrue("command 必须通过短锁 helper 获取句柄", commandSources.contains("mobile_plugin_handle()?"))
        assertTrue("command 不得直接持锁跨 run_mobile_plugin", !commandSources.contains("plugin_handle.lock()"))
    }
}
